name: Predictive Maintenance

on:
  push:
    branches:
      - main  # Automatically triggers on push to the main branch

jobs:   

  deploy-hosting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: pip install -r Predictive_Maintenance/requirements.txt
      - name: Push files to Frontend Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python Predictive_Maintenance/hosting/hosting.py
